### ISSUE TITLE
Rule manager must be started first!

### ISSUE THREAD

**Issue by bl4ckh4t3** [redhat-italy/hacep#79]
When a node is started while other nodes are inserting facts in grid, this exception arises.

[hacep.txt](https://github.com/redhat-italy/hacep/files/903267/hacep.txt)

**Comment by valdar** [comment]
Hi,
thank for reporting this.

I'm assuming you have built the master branch; May I ask you the steps to reproduce this and what configuration have you used? i.e. number of nodes and was it using the jvm playground or eap playground or?

tnx!
